########################
# 服务器相关配置
########################
server:
  port: 8510

########################
# 服务器相关配置
########################
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
########################
# spring 相关配置
########################
spring:
  application:
    #启动名称
    name: HYSTRIX-CONSUMER-FALLBACK
########################
# feign 相关配置
########################
feign:
  hystrix:
    #打开hystrix
    enabled: true

