########################
# 服务器相关配置
########################
server:
  port: 8320
########################
# eureka相关配置
########################
eureka:
  client:
    service-url:
      #eureka 注册中心的地址
     defaultZone: http://localhost:8761/eureka/
########################
# spring 相关配置
########################
spring:
  application:
    name: FEIGN-HELLO-CONSUMER

